export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <title className="title-red">
        Flexy
      </title>
      <link rel="icon" type="image/x-icon" href="emoji.ico"></link>
      <meta charset="UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <body>{children}</body>
    </html>
  )
}
